version: '3.4'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./src/main/resources/static/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    depends_on:
      - prometheus
    volumes:
      - ./src/main/resources/static/monitoring/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./src/main/resources/static/monitoring/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./src/main/resources/static/monitoring/dashboard.json:/etc/dashboards/spring-boot-grafana-dashboard.json:rw
    ports:
      - 3000:3000
